
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin tmp/slc6_amd64_gcc530/src/CondFormats/HIObjects/src/CondFormatsHIObjects/a/CondFormatsHIObjects_xr.cc_tmp
 "LCGReflex/CentralityTable",
 "LCGReflex/CentralityTable::BinValues",
 "LCGReflex/CentralityTable::CBin",
 "LCGReflex/std::vector<CentralityTable::CBin>",
 "LCGReflex/vector<CentralityTable::CBin>",
 "LCGReflex/RPFlatParams",
 "LCGReflex/RPFlatParams::EP",
 "LCGReflex/std::vector<RPFlatParams::EP>",
 "LCGReflex/vector<RPFlatParams::EP>",
 "LCGReflex/UETable",
//--End   tmp/slc6_amd64_gcc530/src/CondFormats/HIObjects/src/CondFormatsHIObjects/a/CondFormatsHIObjects_xr.cc_tmp
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{
names = clnames;
n = sizeof(clnames)/sizeof(char*);
}
